Repository adrielgorosito/sdg_oc_be, pull requests merged in 2025-03, with the labels that each got.

#25 tipo_detalle column
  src/cliente/cliente.service.ts
  src/common/decorators/validate-tipo-receta.decorator.ts
  src/common/enums/tipo-receta.enum.ts
  src/detalles-receta-lentes-aereos/dto/create-detalles-receta-lentes-aereos.dto.ts
  src/detalles-receta-lentes-aereos/entities/detalles-receta-lentes-aereos.entity.ts
  src/receta-lentes-aereos/dto/create-receta-lentes-aereos.dto.ts
  src/receta-lentes-aereos/entities/receta-lentes-aereos.entity.ts
Labels: business rule

#26 PDF upload on audiometria entity
  package-lock.json
  package.json
  src/audiometria/audiometria.controller.ts
  src/audiometria/audiometria.service.ts
  src/audiometria/dto/create-audiometria.dto.ts
  src/audiometria/entities/audiometria.entity.ts
  tsconfig.json
Labels: feature

#27 Producto relationship
  src/venta/venta.service.ts
Labels: enhancement

#28 Multiple fixes
  src/cliente/cliente.controller.ts
  src/cliente/cliente.service.ts
  src/receta-lentes-aereos/receta-lentes-aereos.service.ts
Labels: feature, enhancement

#29 historiaClinicaLentesContacto relationship
  src/cliente/cliente.service.ts
  src/receta-lentes-contacto/dto/create-receta-lentes-contacto.dto.ts
  src/receta-lentes-contacto/entities/receta-lentes-contacto.entity.ts
Labels: enhancement

#31 Facturador
  AFIP/202502191705-LoginTicketRequest.xml
  AFIP/202502191705-LoginTicketRequest.xml.cms-DER
  AFIP/202502191705-LoginTicketRequest.xml.cms-DER-b64
  AFIP/202502191705-loginTicketResponse.xml
  AFIP/202502191851-LoginTicketRequest.xml
  AFIP/202502191851-LoginTicketRequest.xml.cms-DER
  AFIP/202502191851-LoginTicketRequest.xml.cms-DER-b64
  AFIP/202502191851-loginTicketResponse.xml
  AFIP/ClavePrivada.key
  AFIP/TestSystem.csr
  AFIP/certificado.crt
  AFIP/certificado.pem
  AFIP/cliente.ps1
  AFIP/content.txt
  database/seed.dump.sql
  package-lock.json
  package.json
  src/app.module.ts
  src/cliente/cliente.controller.ts
  src/cliente/cliente.service.ts
  src/cliente/dto/create-cliente.dto.ts
  src/cliente/entities/cliente.entity.ts
  src/cliente/enums/tipo-documento.enum.ts
  src/common/decorators/validate-documento.decorator.ts
  src/common/decorators/validate-tipo-documento.decorator.ts
  src/common/entities/baseTransactional.entity.ts
  src/config/database.service.ts
  src/config/typeorm.config.ts
  src/facturador/data/tipo-comprobante.json
  src/facturador/data/tipo-documento.json
  src/facturador/entities/factura.entity.ts
  src/facturador/entities/token.entity.ts
  src/facturador/enums/condicion-iva.enum.ts
  src/facturador/enums/tipo-comprobante.enum.ts
  src/facturador/enums/tipo-documento.enum.ts
  src/facturador/errors/afip.errors.ts
  src/facturador/facturador.controller.ts
  src/facturador/facturador.module.ts
  src/facturador/interfaces/IComprobantes.ts
  src/facturador/interfaces/IConfigServices.ts
  src/facturador/interfaces/ISoap.ts
  src/facturador/services/afip.service.ts
  src/facturador/services/facturador.service.ts
  src/facturador/utils/afip.constantes.ts
  src/facturador/utils/afip.urls.ts
  src/facturador/utils/helpers.ts
  src/producto/producto.service.ts
  src/proveedor/dto/create-proveedor.dto.ts
  src/proveedor/entities/proveedor.entity.ts
  src/venta/dto/create-venta.dto.ts
  src/venta/entities/venta.entity.ts
  src/venta/utils/factura.utils.ts
  src/venta/venta.controller.ts
  src/venta/venta.module.ts
  src/venta/venta.service.ts
Labels: feature

#32 Deleted unnecessary columns and modified types
  database/seed.dump.sql
  src/detalles-receta-lentes-aereos/dto/create-detalles-receta-lentes-aereos.dto.ts
  src/detalles-receta-lentes-aereos/entities/detalles-receta-lentes-aereos.entity.ts
Labels: enhancement, business rule

#34 Deleted observaciones column from DetallesRecetaLentesAereos and added to RecetaLentesAereos
  database/seed.dump.sql
  src/detalles-receta-lentes-aereos/dto/create-detalles-receta-lentes-aereos.dto.ts
  src/detalles-receta-lentes-aereos/entities/detalles-receta-lentes-aereos.entity.ts
  src/receta-lentes-aereos/dto/create-receta-lentes-aereos.dto.ts
  src/receta-lentes-aereos/entities/receta-lentes-aereos.entity.ts
Labels: business rule

#35 Entidad ObraSocialVentas agregada
  .gitignore
  AFIP/202502191705-LoginTicketRequest.xml
  AFIP/202502191705-LoginTicketRequest.xml.cms-DER
  AFIP/202502191705-LoginTicketRequest.xml.cms-DER-b64
  AFIP/202502191705-loginTicketResponse.xml
  AFIP/202502191851-LoginTicketRequest.xml
  AFIP/202502191851-LoginTicketRequest.xml.cms-DER
  AFIP/202502191851-LoginTicketRequest.xml.cms-DER-b64
  AFIP/202502191851-loginTicketResponse.xml
  database/seed.dump.sql
  src/app.module.ts
  src/cliente/dto/create-cliente.dto.ts
  src/cliente/entities/cliente.entity.ts
  src/cliente/enums/tipo-documento.enum.ts
  src/common/decorators/validate-tipo-documento.decorator.ts
  src/facturador/entities/comprobante.entity.ts
  src/facturador/enums/condicion-iva.enum.ts
  src/facturador/facturador.module.ts
  src/facturador/services/facturador.service.ts
  src/obra-social/entities/obra-social.entity.ts
  src/venta-obra-social/dto/create-venta-obra-social.dto.ts
  src/venta-obra-social/entities/venta-obra-social.entity.ts
  src/venta-obra-social/venta-obra-social.controller.spec.ts
  src/venta-obra-social/venta-obra-social.controller.ts
  src/venta-obra-social/venta-obra-social.module.ts
  src/venta-obra-social/venta-obra-social.service.spec.ts
  src/venta-obra-social/venta-obra-social.service.ts
  src/venta/dto/create-venta.dto.ts
  src/venta/entities/venta.entity.ts
  src/venta/utils/factura.utils.ts
  src/venta/venta.module.ts
  src/venta/venta.service.ts
Labels: feature

#36 camelCase Filters fixed
  src/cliente/cliente.service.ts
  src/producto/producto.service.ts
Labels: bug

#40 Hotfix for Venta module
  src/venta/venta.module.ts
Labels: bug

#41 Feature/recetas cliente
  src/pruebas-lentes-contacto/dto/create-pruebas-lentes-contacto.dto.ts
  src/pruebas-lentes-contacto/entities/pruebas-lentes-contacto.entity.ts
  src/receta-lentes-contacto/dto/create-receta-lentes-contacto.dto.ts
  src/receta-lentes-contacto/entities/receta-lentes-contacto.entity.ts
  src/receta-lentes-contacto/receta-lentes-contacto.controller.ts
  src/receta-lentes-contacto/receta-lentes-contacto.service.ts
Labels: bug, enhancement

#43 File uploading for 'Productos' entity
  database/seed.dump.sql
  productos_template/productos_template_v1.xlsm
  productos_template/productos_template_v2.xlsm
  src/producto/dto/create-producto.dto.ts
  src/producto/entities/producto.entity.ts
  src/producto/enums/categoria.enum.ts
  src/producto/producto.controller.ts
  src/producto/producto.module.ts
  src/producto/producto.service.ts
  src/producto/utils/excel.service.ts
  src/venta/venta.service.ts
Labels: feature

#46 Fixed update and create methods where Obra Social doesn't exists
  src/cliente/cliente.module.ts
  src/cliente/cliente.service.ts
Labels: bug, enhancement

#47 Updated producto entity: renamed columns 'precio' to 'precioLista' and 'precioSugerido' to 'precio'
  database/seed.dump.sql
  src/app.module.ts
  src/producto/dto/create-producto.dto.ts
  src/producto/entities/producto.entity.ts
  src/producto/utils/excel.service.ts
Labels: business rule

#48 Added new endpoint to get movimientos from cuenta corriente by cliente id
  database/seed.dump.sql
  src/cuenta-corriente/cuenta-corriente.controller.ts
  src/cuenta-corriente/cuenta-corriente.service.ts
Labels: feature

#49 Fixed comprobantes self relationship and added new endpoint to get all comprobantes by cliente id
  database/seed.dump.sql
  src/facturador/comprobante.controller.ts
  src/facturador/entities/comprobante.entity.ts
  src/facturador/services/facturador.service.ts
Labels: bug, feature

#50 Paginacion de ventas con fechas y algunos arrelgo de bugs
  src/cliente/cliente.service.ts
  src/venta-obra-social/dto/create-venta-obra-social.dto.ts
  src/venta/dto/paginate-venta.dto.ts
  src/venta/entities/venta.entity.ts
  src/venta/venta.controller.ts
  src/venta/venta.service.ts
Labels: feature

#51 filtro del genero agregado
  src/cliente/cliente.service.ts
  src/cliente/dto/paginate-cliente.dto.ts
Labels: feature

#54 Rename factura
  src/app.module.ts
  src/cliente/dto/create-cliente.dto.ts
  src/cliente/entities/cliente.entity.ts
  src/common/decorators/validate-tipo-documento.decorator.ts
  src/comprobante/comprobante.controller.ts
  src/comprobante/comprobante.module.ts
  src/comprobante/dto/create-comprobante.dto.ts
  src/comprobante/dto/paginate-comprobante.dto.ts
  src/comprobante/entities/comprobante.entity.ts
  src/comprobante/entities/token.entity.ts
  src/comprobante/enums/condicion-iva.enum.ts
  src/comprobante/enums/tipo-comprobante.enum.ts
  src/comprobante/enums/tipo-documento.enum.ts
  src/comprobante/errors/afip.errors.ts
  src/comprobante/interfaces/IComprobantes.ts
  src/comprobante/interfaces/IConfigServices.ts
  src/comprobante/interfaces/IDatosDocumentos.ts
  src/comprobante/interfaces/ISoap.ts
  src/comprobante/services/afip.service.ts
  src/comprobante/services/comprobante.service.ts
  src/comprobante/services/generador-documentos.service.ts
  src/comprobante/utils/afip.constantes.ts
  src/comprobante/utils/afip.urls.ts
  src/comprobante/utils/comprobante.utils.ts
  src/comprobante/utils/helpers.ts
  src/comprobante/utils/mapeosEnums.ts
  src/facturador/data/tipo-comprobante.json
  src/facturador/data/tipo-documento.json
  src/venta-obra-social/dto/create-venta-obra-social.dto.ts
  src/venta-obra-social/entities/venta-obra-social.entity.ts
  src/venta/dto/create-venta.dto.ts
  src/venta/dto/paginate-venta.dto.ts
  src/venta/entities/venta.entity.ts
  src/venta/venta.controller.ts
  src/venta/venta.module.ts
  src/venta/venta.service.ts
Labels: feature

#55 Actualiza la configuración de límites de ThrottlerModule a 100, mejor…
  src/app.module.ts
  src/cliente/cliente.service.ts
  src/comprobante/interfaces/IDatosDocumentos.ts
  src/comprobante/services/comprobante.service.ts
  src/comprobante/services/generador-documentos.service.ts
  src/comprobante/utils/comprobante.utils.ts
  src/comprobante/utils/mapeosEnums.ts
  src/venta/venta.service.ts
Labels: feature

#57 factura solved
  src/app.module.ts
  src/comprobante/services/afip.service.ts
  src/comprobante/services/comprobante.service.ts
  src/comprobante/utils/comprobante.utils.ts
  src/comprobante/utils/helpers.ts
  src/config/database.service.ts
Labels: feature
