Repository adrielgorosito/sdg_oc_be, pull requests merged in 2025-04, with the labels that each got.

#59 Refactoriza la validación de forma de pago en el decorador y elimina …
  src/caja/caja.controller.spec.ts
  src/caja/caja.controller.ts
  src/caja/caja.module.ts
  src/caja/caja.service.spec.ts
  src/caja/caja.service.ts
  src/caja/dto/create-caja.dto.ts
  src/caja/dto/update-caja.dto.ts
  src/caja/entities/caja.entity.ts
  src/common/decorators/is-forma-pago.decorator.ts
  src/common/enums/forma-pago.enum.ts
  src/common/enums/tipo-movimiento.enum.ts
  src/cuenta-corriente/cuenta-corriente.controller.ts
  src/cuenta-corriente/cuenta-corriente.module.ts
  src/cuenta-corriente/cuenta-corriente.service.ts
  src/movimiento/dto/create-movimiento.dto.ts
  src/venta/venta.service.ts
Labels: feature

#61 Feature/email
  database/seed.dump.sql
  package-lock.json
  package.json
  src/app.module.ts
  src/cliente/cliente.module.ts
  src/cliente/cliente.service.ts
  src/comprobante/comprobante.controller.ts
  src/comprobante/comprobante.module.ts
  src/comprobante/dto/create-comprobante.dto.ts
  src/comprobante/dto/email-data.dto.ts
  src/comprobante/entities/comprobante.entity.ts
  src/comprobante/interfaces/IDatosDocumentos.ts
  src/comprobante/services/comprobante.service.ts
  src/comprobante/services/email.service.ts
  src/comprobante/services/generador-documentos.service.ts
  src/comprobante/utils/comprobante.utils.ts
  src/comprobante/utils/mapeosEnums.ts
  src/config/database.service.ts
  src/cuenta-corriente/cuenta-corriente.controller.ts
  src/cuenta-corriente/cuenta-corriente.service.ts
  src/cuenta-corriente/dto/paginate-cc.dto.ts
  src/venta/entities/venta.entity.ts
  src/venta/venta.service.ts
Labels: feature

#62 …comprobante para incluir la relación con la factura.
  src/comprobante/services/comprobante.service.ts
  src/venta/venta.service.ts
Labels: bug

#63 Feature/producto
  src/caja/caja.controller.ts
  src/caja/caja.service.ts
  src/producto/dto/update-precio-producto.dto.ts
  src/producto/producto.controller.ts
  src/producto/producto.service.ts
Labels: feature

#64 Agrega el método findCierreDelDia en CajaController y su implementaci…
  src/caja/caja.controller.ts
  src/caja/caja.service.ts
  src/comprobante/services/comprobante.service.ts
  src/comprobante/services/generador-documentos.service.ts
  src/comprobante/utils/comprobante.utils.ts
Labels: feature

#65 CuentaCorriente
  src/cuenta-corriente/cuenta-corriente.service.ts
Labels: bug

#66 Reportes
  src/venta-obra-social/venta-obra-social.controller.ts
  src/venta-obra-social/venta-obra-social.module.ts
  src/venta-obra-social/venta-obra-social.service.ts
Labels: feature

#67 Reporte
  src/venta-obra-social/venta-obra-social.controller.ts
  src/venta-obra-social/venta-obra-social.service.ts
Labels: feature

#68 upgrade reporte
  src/cuenta-corriente/cuenta-corriente.service.ts
  src/venta-obra-social/venta-obra-social.service.ts
Labels: feature

#69 agregar ventaId
  src/venta-obra-social/venta-obra-social.service.ts
Labels: feature

#70 order caja y cambio email
  src/caja/caja.service.ts
  src/comprobante/services/email.service.ts
Labels: feature

#72 return role on JWT
  src/auth/auth.service.ts
Labels: feature

#73 Desactivar la eliminación del esquema en la configuración de la base …
  src/app.module.ts
  src/config/database.service.ts
  src/producto/dto/create-producto.dto.ts
  src/producto/entities/producto.entity.ts
  src/producto/producto.service.ts
  src/producto/utils/excel.service.ts
  src/producto/utils/generador-codigo.ts
  src/venta/venta.service.ts
Labels: feature

#74 Agregar dependencias de @nestjs/schedule y date-fns-tz, implementar scheduleModule en app.module.ts, y añadir lógica de cron en CajaService para manejar cierres automáticos. También se realizan ajustes en la validación de fechas y en la creación de movimientos en CuentaCorrienteService y VentaService.
  package-lock.json
  package.json
  src/app.module.ts
  src/caja/caja.service.ts
  src/cuenta-corriente/cuenta-corriente.service.ts
  src/movimiento/dto/create-movimiento.dto.ts
  src/venta/dto/create-venta.dto.ts
  src/venta/venta.service.ts
Labels: bug

#75 Actualizar el volcado de la base de datos, desactivar la sincronizaci…
  database/seed.dump.sql
  src/app.module.ts
  src/caja/caja.service.ts
  src/cliente/dto/create-cliente.dto.ts
  src/comprobante/services/comprobante.service.ts
  src/config/database.service.ts
  src/config/typeorm.config.ts
  src/venta/venta.service.ts
Labels: bug

#80 BUGS
  src/comprobante/services/afip.service.ts
  src/comprobante/services/comprobante.service.ts
  src/comprobante/utils/helpers.ts
  src/proveedor/dto/create-proveedor.dto.ts
Labels: bug

#82 Feature/notas
  src/audiometria/audiometria.service.ts
  src/caja/caja.service.ts
  src/cliente/cliente.service.ts
  src/comprobante/comprobante.controller.ts
  src/comprobante/services/afip.service.ts
  src/comprobante/services/comprobante.service.ts
  src/comprobante/services/generador-documentos.service.ts
  src/comprobante/utils/comprobante.utils.ts
  src/comprobante/utils/helpers.ts
  src/proveedor/dto/create-proveedor.dto.ts
  src/venta/venta.module.ts
  src/venta/venta.service.ts
Labels: feature

#83 Development
  src/audiometria/audiometria.service.ts
  src/caja/caja.service.ts
  src/comprobante/comprobante.controller.ts
  src/comprobante/services/comprobante.service.ts
  src/comprobante/services/generador-documentos.service.ts
  src/comprobante/utils/comprobante.utils.ts
  src/venta/venta.module.ts
  src/venta/venta.service.ts
Labels: business rule

#84 Feature/cliente
  src/caja/caja.service.ts
  src/cliente/cliente.controller.ts
  src/cliente/cliente.service.ts
  src/venta/venta.service.ts
Labels: bug, feature

#85 Development
  src/caja/caja.service.ts
  src/cliente/cliente.controller.ts
  src/cliente/cliente.service.ts
  src/venta/venta.service.ts
Labels: feature

#88 Refactoriza consultas en varios servicios para mejorar la búsqueda y optimiza el manejo de excepciones en AudiometriaService y UploadService. Se añaden validaciones en CajaService y VentaService para evitar operaciones no permitidas.
  src/audiometria/audiometria.controller.ts
  src/audiometria/audiometria.service.ts
  src/caja/caja.service.ts
  src/cliente/cliente.service.ts
  src/common/upload/upload.service.ts
  src/comprobante/services/afip.service.ts
  src/comprobante/services/comprobante.service.ts
  src/cuenta-corriente/cuenta-corriente.service.ts
  src/producto/producto.service.ts
  src/venta/venta.service.ts
Labels: bug

#90 Feature/comprobante
  package-lock.json
  package.json
  src/app.module.ts
  src/comprobante/comprobante.controller.ts
  src/comprobante/services/comprobante.service.ts
  src/cuenta-corriente/cuenta-corriente.service.ts
  src/ocr/ocr.controller.ts
  src/ocr/ocr.module.ts
  src/ocr/ocr.service.ts
  src/venta/dto/paginate-venta.dto.ts
  src/venta/venta.service.ts
Labels: bug, feature
