Repository adrielgorosito/sdg_oc_be, pull requests merged in 2025-02, with the labels that each got.

#9 RelationDTO, LineaVenta Entity and VentaEntity created
  src/app.module.ts
  src/linea-venta/dto/create-linea-venta.dto.ts
  src/linea-venta/dto/update-linea-venta.dto.ts
  src/linea-venta/entities/linea-venta.entity.ts
  src/linea-venta/linea-venta.controller.spec.ts
  src/linea-venta/linea-venta.controller.ts
  src/linea-venta/linea-venta.module.ts
  src/linea-venta/linea-venta.service.spec.ts
  src/linea-venta/linea-venta.service.ts
Labels: feature, enhancement

#10 Code formatting, bugs fixes and Movimiento new entity
  src/app.module.ts
  src/cliente-obra-social/cliente-obra-social.controller.ts
  src/cliente-obra-social/cliente-obra-social.service.ts
  src/cliente-obra-social/dto/create-cliente-obra-social.dto.ts
  src/cliente-obra-social/dto/update-cliente-obra-social.dto.ts
  src/cliente/entities/cliente.entity.ts
  src/cuenta-corriente/cuenta-corriente.controller.ts
  src/cuenta-corriente/cuenta-corriente.service.ts
  src/cuenta-corriente/dto/create-cuenta-corriente.dto.ts
  src/cuenta-corriente/dto/update-cuenta-corriente.dto.ts
  src/cuenta-corriente/entities/cuenta-corriente.entity.ts
  src/marcas/marcas.controller.ts
  src/marcas/marcas.service.ts
  src/movimiento/dto/create-movimiento.dto.ts
  src/movimiento/dto/update-movimiento.dto.ts
  src/movimiento/entities/movimiento.entity.ts
  src/movimiento/movimiento.controller.spec.ts
  src/movimiento/movimiento.controller.ts
  src/movimiento/movimiento.module.ts
  src/movimiento/movimiento.service.spec.ts
  src/movimiento/movimiento.service.ts
  src/obra-social/dto/create-obra-social.dto.ts
  src/obra-social/dto/update-obra-social.dto.ts
  src/obra-social/obra-social.controller.ts
  src/obra-social/obra-social.service.ts
  src/productos/productos.controller.ts
  src/productos/productos.service.ts
  src/proveedor/proveedor.controller.ts
  src/proveedor/proveedor.service.ts
Labels: bug, feature, enhancement

#11 Feature/ventas
  .vscode/launch.json
  src/app.module.ts
  src/common/dtos/relation.dto.ts
  src/common/entities/base.entity.ts
  src/common/entities/baseTransactional.entity.ts
  src/linea-venta/dto/create-linea-venta.dto.ts
  src/linea-venta/entities/linea-venta.entity.ts
  src/main.ts
  src/marca/dto/create-marca.dto.ts
  src/marca/dto/update-marca.dto.ts
  src/marca/entities/marca.entity.ts
  src/marca/marca.controller.spec.ts
  src/marca/marca.controller.ts
  src/marca/marca.module.ts
  src/marca/marca.service.spec.ts
  src/marca/marca.service.ts
  src/marcas/marcas.controller.ts
  src/producto/dto/create-producto.dto.ts
  src/producto/dto/update-producto.dto.ts
  src/producto/entities/producto.entity.ts
  src/producto/producto.controller.spec.ts
  src/producto/producto.controller.ts
  src/producto/producto.module.ts
  src/producto/producto.service.spec.ts
  src/producto/producto.service.ts
  src/productos/productos.controller.ts
  src/proveedor/dto/create-proveedor.dto.ts
  src/proveedor/entities/proveedor.entity.ts
  src/proveedor/proveedor.module.ts
  src/proveedor/proveedor.service.ts
  src/venta/dto/create-venta.dto.ts
  src/venta/dto/update-venta.dto.ts
  src/venta/entities/venta.entity.ts
  src/venta/venta.controller.spec.ts
  src/venta/venta.controller.ts
  src/venta/venta.module.ts
  src/venta/venta.service.spec.ts
  src/venta/venta.service.ts
Labels: enhancement

#14 Venta logic
  src/app.module.ts
  src/common/entities/base.entity.ts
  src/common/entities/baseTransactional.entity.ts
  src/linea-venta/dto/create-linea-venta.dto.ts
  src/linea-venta/entities/linea-venta.entity.ts
  src/marca/marca.service.ts
  src/medio-de-pago/dto/create-medio-de-pago.dto.ts
  src/medio-de-pago/dto/update-medio-de-pago.dto.ts
  src/medio-de-pago/entities/medio-de-pago.entity.ts
  src/medio-de-pago/enum/medio-de-pago.enum.ts
  src/medio-de-pago/medio-de-pago.controller.spec.ts
  src/medio-de-pago/medio-de-pago.controller.ts
  src/medio-de-pago/medio-de-pago.module.ts
  src/medio-de-pago/medio-de-pago.service.spec.ts
  src/medio-de-pago/medio-de-pago.service.ts
  src/producto/producto.service.ts
  src/proveedor/proveedor.service.ts
  src/venta/dto/create-venta.dto.ts
  src/venta/dto/update-venta.dto.ts
  src/venta/entities/venta.entity.ts
  src/venta/venta.controller.ts
  src/venta/venta.service.ts
Labels: feature

#16 Localidad and Provincia endpoints
  src/app.module.ts
  src/cliente/entities/cliente.entity.ts
  src/localidad/dto/create-localidad.dto.ts
  src/localidad/dto/update-localidad.dto.ts
  src/localidad/entities/localidad.entity.ts
  src/localidad/localidad.controller.spec.ts
  src/localidad/localidad.controller.ts
  src/localidad/localidad.module.ts
  src/localidad/localidad.service.spec.ts
  src/localidad/localidad.service.ts
  src/localidad/localidad.spec.ts
  src/provincia/dto/create-provincia.dto.ts
  src/provincia/dto/update-provincia.dto.ts
  src/provincia/entities/provincia.entity.ts
  src/provincia/provincia.controller.spec.ts
  src/provincia/provincia.controller.ts
  src/provincia/provincia.module.ts
  src/provincia/provincia.service.spec.ts
  src/provincia/provincia.service.ts
  src/provincia/provincia.spec.ts
Labels: enhancement

#20 Refactor and clean up project structure:
  src/app.module.ts
  src/cliente/cliente.service.ts
  src/cliente/dto/create-cliente.dto.ts
  src/common/decorators/validate-tipo-receta.decorator.ts
  src/common/entities/base.entity.ts
  src/detalles-receta-lentes-aereos/detalles-receta-lentes-aereos.service.ts
  src/detalles-receta-lentes-aereos/dto/create-detalles-receta-lentes-aereos.dto.ts
  src/detalles-receta-lentes-aereos/entities/detalles-receta-lentes-aereos.entity.ts
  src/historia-clinica-lentes-contacto/dto/create-historia-clinica-lentes-contacto.dto.ts
  src/historia-clinica-lentes-contacto/entities/historia-clinica-lentes-contacto.entity.ts
  src/linea-venta/linea-venta.controller.spec.ts
  src/linea-venta/linea-venta.controller.ts
  src/linea-venta/linea-venta.module.ts
  src/linea-venta/linea-venta.service.spec.ts
  src/linea-venta/linea-venta.service.ts
  src/medio-de-pago/medio-de-pago.controller.spec.ts
  src/medio-de-pago/medio-de-pago.controller.ts
  src/medio-de-pago/medio-de-pago.module.ts
  src/medio-de-pago/medio-de-pago.service.spec.ts
  src/medio-de-pago/medio-de-pago.service.ts
  src/pruebas-lentes-contacto/dto/create-pruebas-lentes-contacto.dto.ts
  src/pruebas-lentes-contacto/entities/pruebas-lentes-contacto.entity.ts
  src/pruebas-lentes-contacto/pruebas-lentes-contacto.controller.spec.ts
  src/pruebas-lentes-contacto/pruebas-lentes-contacto.controller.ts
  src/pruebas-lentes-contacto/pruebas-lentes-contacto.module.ts
  src/pruebas-lentes-contacto/pruebas-lentes-contacto.service.spec.ts
  src/pruebas-lentes-contacto/pruebas-lentes-contacto.service.ts
  src/receta-lentes-aereos/dto/create-receta-lentes-aereos.dto.ts
  src/receta-lentes-aereos/entities/receta-lentes-aereos.entity.ts
  src/receta-lentes-aereos/receta-lentes-aereos.service.ts
  src/receta-lentes-contacto/dto/create-receta-lentes-contacto.dto.ts
  src/receta-lentes-contacto/entities/receta-lentes-contacto.entity.ts
  src/receta-lentes-contacto/receta-lentes-contacto.service.ts
Labels: feature

#21 Minor fixes
  src/app.module.ts
  src/audiometria/audiometria.service.ts
  src/auth/auth.guard.ts
  src/auth/auth.service.ts
  src/cliente-obra-social/cliente-obra-social.service.ts
  src/cliente/cliente.controller.ts
  src/cliente/cliente.service.ts
  src/common/decorators/unique-obra-social.decorator.ts
  src/cuenta-corriente/cuenta-corriente.service.ts
  src/detalles-receta-lentes-aereos/detalles-receta-lentes-aereos.service.ts
  src/historia-clinica-lentes-contacto/historia-clinica-lentes-contacto.service.ts
  src/localidad/localidad.service.ts
  src/marca/marca.service.ts
  src/movimiento/movimiento.service.ts
  src/obra-social/obra-social.service.ts
  src/producto/producto.service.ts
  src/proveedor/proveedor.service.ts
  src/provincia/provincia.service.ts
  src/receta-lentes-aereos/receta-lentes-aereos.service.ts
  src/receta-lentes-contacto/dto/create-receta-lentes-contacto.dto.ts
  src/receta-lentes-contacto/entities/receta-lentes-contacto.entity.ts
  src/receta-lentes-contacto/receta-lentes-contacto.service.ts
  src/user/roles.guard.ts
  src/user/user.service.ts
  src/venta/venta.service.ts
Labels: bug, enhancement, business rule

#22 Feature/pagination
  src/common/dtos/pagination.dto.ts
  src/producto/dto/create-producto.dto.ts
  src/producto/dto/paginate-producto.dto.ts
  src/producto/entities/producto.entity.ts
  src/producto/enums/categoria.enum.ts
  src/producto/producto.controller.ts
  src/producto/producto.service.ts
Labels: feature
